-- Auto-generated by B-2 Ordnance Personalization System
ordnance_manifest = {
    slot1 = { serial = "MOAB-2026-0061", text = "EAT SHIT!", medium = "marker" },
    slot2 = { serial = "MOAB-2026-0062", text = "ENJOY!", medium = "chalk" },
}
